TOP_ALTCOINS = [

    # Layer 1 / Layer 2
    "SEIUSDT",
    "TIAUSDT",
    "OPUSDT",
    "STRKUSDT",
    "ZKUSDT",
    "EGLDUSDT",
    "IOTAUSDT",
    "CFXUSDT",
    "STXUSDT",
    "SUIUSDT",
    "NEARUSDT",
    "APTUSDT",
    "ATOMUSDT",
    "AVAXUSDT",
    "ADAUSDT",
    "DOTUSDT",
    "ICPUSDT",
    "TRXUSDT",
    "XRPUSDT",
    "SOLUSDT",

    # AI / DePIN
    "AKTUSDT",
    "AIOZUSDT",
    "GRASSUSDT",
    "ATHUSDT",
    "RENDERUSDT",
    "FETUSDT",

    # DeFi
    "RUNEUSDT",
    "DYDXUSDT",
    "PENDLEUSDT",
    "COMPUSDT",
    "CRVUSDT",
    "LDOUSDT",
    "AAVEUSDT",
    "UNIUSDT",
    "JTOUSDT",
    "RAYUSDT",
    "GMXUSDT",

    # Infrastructure
    "ARUSDT",
    "EIGENUSDT",
    "ENSUSDT",
    "PYTHUSDT",
    "ORDIUSDT",
    "ZROUSDT",
    "IMXUSDT",
    "THETAUSDT",
    "TFUELUSDT",
    "LINKUSDT",
    "FILUSDT",

    # Старі перевірені
    "ETHUSDT"
    "NEOUSDT",
    "KAVAUSDT",
    "ONTUSDT",
    "QTUMUSDT",
    "ZRXUSDT",
    "RVNUSDT",
    "GASUSDT",
    "BATUSDT",
    "CHZUSDT",
    "GRTUSDT",
    "XNOUSDT",
    "KSMUSDT",
    "YFIUSDT",
    "SNXUSDT",
    "ELFUSDT",
    "ENJUSDT",
    "MANAUSDT",
    "GALAUSDT",
    "ROSEUSDT",
    "MINAUSDT"
]